name: CI
on: [push, pull_request]
jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Test
        run: go test -count=1 -v ./...
      - name: Vet
        run: go vet ./...
      - uses: reviewdog/action-staticcheck@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Format
        run: |
          gofmt -d . > format.patch;
          DIFF=$(cat format.patch);
          if [[ $DIFF != "" ]];
          then
            cat format.patch;
            exit 1;
          fi
